apiVersion: v1
kind: Service
metadata:
  name: calc-react-service
spec:
  selector:
    app: calc-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
